image: golang

stages:
    - build
    - release

build-client:
    stage: build
    image: node
    artifacts:
        paths:
            - app/build
    script:
        - cd app/
        - npm install
        - npm run build

build-server:
    stage: build
    image: mgkeiji/gogcc
    artifacts:
        paths:
            - .env
            - app/build
            - todoApp
    script:
        - go build

release:
    stage: release
    only:
        - master
    image: docker:19.03.12
    services:
        - docker:19.03.12-dind
    script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t registry.gitlab.com/mkeiji/ktodoapp:latest .
        - docker push registry.gitlab.com/mkeiji/ktodoapp:latest
